### ISSUE TITLE
Is the logic behind 'data-select-all' by any chance reversed?

### ISSUE THREAD

**Issue by LeoEurope** [codeshackio/multi-select-dropdown-js#2]
By default the dropdown shows a 'Select all' button, that is what the documentation states as well.

If, however, I wish to remove that button I have to set `data-select-all` to True because when I set it to False it will actually display the 'Select all' button, exactly the opposite from what is expected and from what the documentation states.

Is this perhaps a logic bug?

**Comment by codeshackio** [comment]
Currently, the class will only check whether the attribute is specified or not to determine whether it's declared. It doesn't take the value into consideration. You can solve it by removing the attribute completely.
